config/routes.rb
Rails.application.routes.draw do
  root 'main#home'
  get 'team', to: 'main#team'
  get 'contact', to: 'main#contact'
  post 'contacted', to: 'emails#create'
  get 'media', to: 'main#media'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

  def create
    if !params[:email].empty? && !params[:message].empty?
      ContactMailer.contact_us(params).deliver
      flash[:notice] = "Thank you for contacting us!"
    else
      flash[:error] = "You're missing an email and/or message contents. Please try again!"
    end
    redirect_to contact_path
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def home
  end

  def team
  end

  def contact
  end

  def media
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AcrossThePark</title>
  <%= stylesheet_link_tag 'reset', media: 'all' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.bpopup.min', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag %>

  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <ul class='sm-links'>
      <li>
        <a href="https://www.facebook.com/ACROSSTHEPARK">
          <%= icon('facebook-square', 'fa-lg') %>
        </a>
      </li>
      <li>
        <a href="https://www.instagram.com/acrosstheparkplay/?hl=en">
          <%= icon('instagram', 'fa-lg') %>
        </a>
      </li>
      <li>
        <a href="https://twitter.com/ATPplay">
          <%= icon('twitter-square', 'fa-lg') %>
        </a>
      </li>
    </ul>
    <div class="links-container">
      <ul class='site-links'>
        <li>
          <a href="/">HOME</a>
        </li>
        <li>
          <a href="team">CAST & CREATIVE</a>
        </li>
        <li>
          <a href="contact">CONTACT</a>
        </li>
        <li>
          <a target="_" class='purple-text' href="https://www.fracturedatlas.org/site/fiscal/profile?id=14612">DONATE</a>
        </li>
        <li>
          <a target="_" class='orange-text' href="http://www.brownpapertickets.com/event/2591970">PURCHASE TICKETS</a>
        </li>
      </ul>
    </div>
    <div class="mobile-menu">
      <a target="_" id="mobile-buy-tix-btn" href="http://www.brownpapertickets.com/event/2591970">BUY TICKETS</a>
      <%= icon('bars', 'fa-lg', 'mobile-menu-icon') %>
      <ul class='mobile-site-links hidden'>
        <li>
          <a href="/">HOME</a>
        </li>
        <li>
          <a href="team">CAST & CREATIVE</a>
        </li>
        <li>
          <a href="contact">CONTACT</a>
        </li>
        <li>
          <a target="_" class='purple-text' href="https://www.fracturedatlas.org/site/fiscal/profile?id=14612">DONATE</a>
        </li>
        <li>
          <a target="_" class='orange-text' href="http://www.brownpapertickets.com/event/2591970">PURCHASE TICKETS</a>
        </li>
      </ul>

    </div>
  </nav>

<%= yield %>

  <footer>
    <ul class='footer-sm-links'>
      <li>
        <a href="https://www.facebook.com/ACROSSTHEPARK">
          <%= icon('facebook-square', 'fa-lg') %>
        </a>
      </li>
      <li>
        <a href="https://www.instagram.com/acrosstheparkplay/?hl=en">
          <%= icon('instagram', 'fa-lg') %>
        </a>
      </li>
      <li>
        <a href="https://twitter.com/ATPplay">
          <%= icon('twitter-square', 'fa-lg') %>
        </a>
      </li>
    </ul>
    <p class="avenir">
      <a href="mailto:acrosstheparkplay@gmail.com">acrosstheparkplay@gmail.com</a>
    </p>
  </footer>

  <script>
  $('.mobile-menu-icon').on('click', function() {
    $('.mobile-site-links').toggleClass('hidden');
  });
  </script>

</body>
</html>

app/views/main/contact.html.erb
<% flash.each do |type, msg| %>
  <%= content_tag :div, sanitize(msg), class: "flash avenir" %>
<% end %>

<div class="contact-page">
  <p class="contact-text">
    Caroline and Denny met online too.
  </p>
  <p class="contact-text">
    Introduce yourself.
  </p>
  <div class="form-container">
    <%= form_tag(contacted_path) do %>
      <div class="input-field">
        <%= label_tag :name %><br>
        <%= text_field_tag :name %>
      </div>
      <div class="input-field">
        <%= label_tag :email, 'Email*' %><br>
        <%= text_field_tag :email %>
      </div>
      <div class="input-field">
        <%= label_tag :subject %><br>
        <%= text_field_tag :subject %>
      </div>
      <div class="input-field">
        <%= label_tag :message, 'Message*' %><br>
        <%= text_area_tag :message %>
      </div>
      <p class='required-info'>
        * indicates required field
      </p>
      <%= submit_tag "Send", class: 'submit-btn avenir' %>
    <% end %>
  </div>
</div>

app/views/main/home.html.erb
<div id="large-hero">
  <%= image_tag('/assets/hero_equity.png', width: '100%') %>
</div>

<div id="small-hero">
  <%= image_tag('/assets/small_hero_equity.png', width: '100%') %>
</div>

<div class="about-container">
  <div class="about-block1 align-top">
    <div class="date-container">
      <div class="dates">
        <div>
          <span id="preview-performance" class="avenir orange-text"> PREVIEW PERFORMANCE!</span>
          <span class="avenir show-wkday">THURSDAY</span>
          <p class="show-datetime phosphate"><span class="purple-text">10/27 </span>  7 PM</p>
        </div>
        <div>
          <span class="avenir show-wkday">FRIDAY</span>
          <p class="show-datetime phosphate"><span class="purple-text">10/28 </span>  8 PM</p>
        </div>
        <div>
          <span class="avenir show-wkday">SATURDAY</span>
          <p class="show-datetime phosphate"><span class="purple-text">10/29 </span>  2 PM</p>
        </div>
        <div>
          <span class="avenir show-wkday">SATURDAY</span>
          <p class="show-datetime phosphate"><span class="purple-text">10/29 </span>  8 PM</p>
        </div>
      </div>
      <a href="http://aracaproject.com">
        <%= image_tag('/assets/aracaproject_logo', class:"araca-img") %>
      </a>
    </div>
  </div>

  <div class="about-block2">
    <div class="summary-container">
      <h2 class='section-title phosphate'>THE PLAY</h2>
      <p class='avenir-thin gray-text summary-text'>Stuck on an island with 8 million people, Caroline and Denny are lonely and over-medicated. Separated by Central Park and almost two decades in age, this dysfunctional pair is brought together online by lust and their inability to cope. ACROSS THE PARK, a new play by Kate Tucker Fahlsing, follows Denny and Caroline’s non-traditional relationship for ten years and about ten thousand text messages. This dark comedy takes a candid look at mental illness, the search for human connection, and what happens when the only person who truly understands you is as damaged as you are.</p>
    <br>
    <br>
    <a href="http://aracaproject.com">
      <%= image_tag('/assets/aracaproject_logo', class:"mobile-araca-img") %>
    </a>
    <br>
      <div class="araca-proj summary-text">
        <p class="avenir-thin align-top">
          ACROSS THE PARK is produced with support from a production award from Northwestern University and <a href="http://aracaproject.com">The Araca Project</a>.
          The Araca Project is an initiative of The Araca Group (producers of <span>Urinetown, Wicked, A View From the Bridge</span>) to foster young entrepreneurs from Syracuse University, University of Michigan, Florida State University, Yale University, and Northwestern University.
        </p>
      </div>
    </div>
  </div>
</div>

<div class="tix-info">
  <a class='donate-btn avenir' target="_" href="http://www.brownpapertickets.com/event/2591970">PURCHASE TICKETS</a>
  <br>
  <a class='donate-btn avenir' target="_" href="https://www.fracturedatlas.org/site/fiscal/profile?id=14612">DONATE NOW</a>
</div>

<div class="testimonials avenir-thin">
  <div class="testimonial align-top">
    <p class="gray-text large-text italics">
      <span class="testimonial-quote">"</span>ACROSS THE PARK is a funny, smart, and surprising new play about mental illness, longing, and the lonely, painful, and quirky journey of being alive. Kate Tucker Fahlsing takes on tough themes without being preachy or predictable, and her play has all the hallmarks of an important new talent: an original voice, a deep sense of empathy, and the courage and conviction to tell the truth.<span class="testimonial-quote">"</span>
    </p>
    <p class="testimonial-credit">
      - <a href="http://www.broadwayworld.com/people/Zayd-Dohrn/">Zayd Dohrn</a>
    </p>
  </div>
  <div class="testimonial align-top">
    <p class="gray-text large-text italics">
      <span class="testimonial-quote">"</span>CHICAGO-- Hey, New York. Meet KTF-a brave, hysterical and [insert your favorite expletive here] important new voice in the American theatre! Before I knew it, I was laughing, crying and caring about her characters-deeply. Get on the train and get ready for an uncomfortably giddy ride to heretofore unexplored stations. Meet KTF and her brilliant ACROSS THE PARK...You're welcome.<span class="testimonial-quote">"</span>
    </p>
    <p class="testimonial-credit">
      - <a href="http://kevinchristopherfox.com/">Kevin Christopher Fox</a>, SDC
    </p>
    <p class="subcredit gray-text">(ATP 10 minute premiere director, first year development director)</p>

  </div>
</div>

<div class="press">
  <h2 class='section-title phosphate'>THE PRESS</h2>
  <a target="_" href="http://www.backstage.com/news/casting/now-casting-across-park-and-3-more-gigs/?utm_source=facebook&utm_medium=social&utm_campaign=Casting%20Posts">
    <div class="align-top press-piece">
      <img src="/assets/nyc-centralpark.jpg" alt="NYC Central Park"/>
      <div class="press-text">
        <p class="phosphate">BACKSTAGE</p>
        <p class="avenir"> Now Casting: ‘Across the Park’ and 3 More Gigs</p>
      </div>
    </div>
  </a>
  <a target="_" href="http://www.upout.com/nyc/do/across-the-park-a-performance">
    <div class="align-top press-piece">
      <img src="/assets/upout_logo.jpg" alt="UpOut"/>
      <div class="press-text">
        <p class="phosphate">UP OUT</p>
        <p class="avenir"> Across the Park: A Performance</p>
      </div>
    </div>
  </a>
  <a target="_" href="http://www.broadwayworld.com/off-broadway/article/The-Araca-Project-Presents-ACROSS-THE-PARK-20161011#and">
    <div class="align-top press-piece">
      <img src="/assets/broadwayworld.jpg" alt="Broadway World"/>
      <div class="press-text">
        <p class="phosphate">BROADWAY WORLD</p>
        <p class="avenir"> The Araca Project Presents<br> ACROSS THE PARK</p>
      </div>
    </div>
  </a>

</div>

<div class="location">
  <p id="where-are-we" class="center-text section-title phosphate">
    WHERE ARE WE?
  </p>
  <p class="center-text avenir">
    314 W 54th St, New York, NY 10019
  </p>
  <div class="map">
    <iframe frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJt-9bhFdYwokR-1tjCK8LPGc&key=AIzaSyBkz6N7JlqvH70mhw7yeGa04AfQjuYBcr0" allowfullscreen></iframe>
  </div>
</div>

app/views/main/media.html.erb
<h2 class="section-title media-title phosphate center-text">PHOTOS</h2>
<div class="carousel-container">
  <span>Drag left or right to scroll through images, or use the Prev/Next buttons below!</span>

  <div class="owl-carousel">
    <div><img src="assets/AtP-8321.jpg" alt="Across The Park Image 1"></div>
    <div><img src="assets/AtP-8333.jpg" alt="Across The Park Image 2"></div>
    <div><img src="assets/AtP-8398.jpg" alt="Across The Park Image 3"></div>
    <div><img src="assets/AtP-8502.jpg" alt="Across The Park Image 5"></div>
    <div><img src="assets/AtP-8560.jpg" alt="Across The Park Image 6"></div>
    <div><img src="assets/AtP-8759.jpg" alt="Across The Park Image 7"></div>
    <div><img src="assets/AtP-8801.jpg" alt="Across The Park Image 8"></div>
    <div><img src="assets/AtP-8837.jpg" alt="Across The Park Image 9"></div>
    <div><img src="assets/AtP-8842.jpg" alt="Across The Park Image 10"></div>
    <div><img src="assets/AtP-8851.jpg" alt="Across The Park Image 11"></div>
    <div><img src="assets/AtP-8897.jpg" alt="Across The Park Image 12"></div>
    <div><img src="assets/AtP-8908.jpg" alt="Across The Park Image 13"></div>
    <div><img src="assets/AtP-8929.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-8952.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-8984.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9054.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9059.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9082.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9091.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9097.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9153.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9171.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9219.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9241.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9253.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9261.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9355.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9393.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9407.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9441.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9446.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9453.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9475.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9561.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9603.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9631.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9663.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9666.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9692.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9750.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9763.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9780.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9783.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9792.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9797.jpg" alt="Across The Park Image 4"></div>
    <div><img src="assets/AtP-9801.jpg" alt="Across The Park Image 4"></div>
  </div>
</div>
<div class="carousel-buttons-container">
  <button class="carousel-prev">Previous</button>
  <button class="carousel-next">Next</button>
</div>

<div class="videos">
  <h2 class='section-title phosphate'>VIDEOS</h2>
  <iframe src="https://player.vimeo.com/video/180106281" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
  <p>TRAILER</p>
  <iframe src="https://player.vimeo.com/video/180106348" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
  <p>FUNDRAISING CAMPAIGN</p>
  <iframe src="https://player.vimeo.com/video/180106133" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
  <p>BLOOPERS</p>
</div>

<script>
$(document).ready(function(){
  var $owl = $('.owl-carousel');

  $owl.owlCarousel({
    center: true,
    margin: 10,
    loop: true,
    autoWidth: true,
  });


  $(".carousel-prev").on('click', function() {
    $owl.trigger('prev.owl.carousel');
  });
  $(".carousel-next").on('click', function() {
    $owl.trigger('next.owl.carousel');
  });
});
</script>